version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
      ExtrenalEventBaseUrl: http://localhost:6081
    ports:
      - "6180:80"
    container_name: eventapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventfinder
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://10.0.0.108:6170
      CallBackUrl: http://localhost:5207
      CartUrl: http://cart
    ports:
      - "5207:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5207
    ports:
      - "6170:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://10.0.0.108:6170
      ConnectionString: basket.data
    ports:
      - "6066:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: eventsqlserver
    ports:
      - "1445:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6078:6379"  
    networks:
      - backend 