version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi1(!)
      ExtrenalEventBaseUrl: http://localhost:6081
    ports:
      - "6081:80"
    container_name: eventapihome
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver1

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventfinderhome
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5208:80"
    networks:
      - frontend
    depends_on:
      - catalog

  mssqlserver1:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi1(!)
    container_name: eventsqlserverhome
    ports:
      - "1446:1433"
    networks:
      - backend