version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
      ExtrenalEventBaseUrl: http://localhost:6180
    ports:
      - "6180:80"
    container_name: eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventfinder
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5207:80"
    networks:
      - frontend
    depends_on:
      - catalog

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: eventsqlserver
    ports:
      - "1445:1433"
    networks:
      - backend
