version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapis
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: TheHapsDb
      DatabaseUser: sa
      DatabasePassword: EventApi1(!)
      ExtrenalEventBaseUrl: http://localhost:6081
    ports:
      - "6081:80"
    container_name: eventapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: events/webmvcs
    container_name: eventfinder
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.38:6071
      CallBackUrl: http://localhost:5209
    ports:
      - "5209:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5209
    ports:
      - "6071:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi1(!)
    container_name: thehapssqlserver
    ports:
      - "1446:1433"
    networks:
      - backend
